### ISSUE TITLE
Porting to Crystal?

### ISSUE THREAD

**Issue by krissemicolon** [timo-cmd2/daphne#7]
I dont know if it's possible but it would sure be a performance improvement.

**Comment by timo-cmd2** [comment]
yeah, I tend to develop it on ruby so we can use it on rubinius. Also I've though about some Ruby FFI

**Comment by timo-cmd2** [comment]
In the end ill simply do a self-hosting rewrite in daphne itselfe, so the host lang shouldn't matter

**Comment by RoeHH** [comment]
Why dont you just compile it to java....
🙄

**Comment by timo-cmd2** [comment]
Why should I. JVM is shit and way more slower than rbx.
